package com.ese.kafka.IT;

import com.ese.kafka.autogenerated.events.user.UserCreatedEvent;
import com.ese.kafka.user.infrastructure.event.consumer.UserKafkaEventConsumer;
import com.ese.kafka.user.infrastructure.event.consumer.specific.UserCreatedSpecificConsumer;
import org.apache.avro.generic.GenericRecord;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@SpringBootTest
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class UserDLT {

    @Autowired
    private KafkaTemplate<String, GenericRecord> kafkaTemplate;

    @Value("${app.kafka.topics.user}")
    private String USER_EVENT_TOPIC;

    @MockitoSpyBean
    private UserKafkaEventConsumer userKafkaEventConsumer;

    @MockitoSpyBean
    private UserCreatedSpecificConsumer userCreatedSpecificConsumer;

    @BeforeEach
    void setup() {
        // Make the specific consumer throw a NullPointerException so it is excluded from retries
        // and routed directly to the DLT per @RetryableTopic(exclude = {NullPointerException.class})
        doThrow(new NullPointerException("forced NPE for DLT"))
                .when(userCreatedSpecificConsumer).accept(any());
    }

    @Test
    void createUser_EventRoutedToDLT_WhenSpecificConsumerThrowsNPE() {
        // Arrange
        UserCreatedEvent event = UserCreatedEvent.newBuilder()
                .setId(999L)
                .setFirstname("DLT")
                .setLastname("Test")
                .setEmail("dlt@test.com")
                .setRole("USER")
                .setTimestamp(System.currentTimeMillis())
                .build();

        // Act
        kafkaTemplate.send(USER_EVENT_TOPIC, event);

        // Assert: verify the DLT handler was invoked
        verify(userKafkaEventConsumer, timeout(10000)).listenDLT(any());
    }
}
