package com.ese.kafka.user.infrastructure.api;

import com.ese.kafka.autogenerated.events.user.UserCreatedEvent;
import com.ese.kafka.common.infrastructure.event.producer.KafkaProducer;
import com.ese.kafka.user.domain.entity.User;
import com.ese.kafka.user.domain.port.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController
@RequestMapping("/api/v1/users")
@RequiredArgsConstructor
public class UserController {

    private final KafkaProducer kafkaProducer;
    private final UserRepository userRepository;

    @GetMapping("/create")
    public void createUser(
            @RequestParam String firstname,
            @RequestParam String lastname,
            @RequestParam String email) {
        System.out.println("Creating user");
        UserCreatedEvent userCreatedEvent = UserCreatedEvent.newBuilder()
                .setId(1)
                .setFirstname(firstname)
                .setLastname(lastname)
                .setEmail(email)
                .setRole("USER")
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send("user.events", userCreatedEvent);
    }

    @GetMapping("/{id}")
    public ResponseEntity<User> getUser(@PathVariable Long id) {
        Optional<User> optionalUser = userRepository.findById(id);

        return optionalUser
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }


}
